services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
  hexplate:
    build: .
    ports:
      - '8000:8000'
    environment:
      MONGO_DSN: "mongodb://mongo:27017"
    develop:
      watch:
        - action: rebuild
          path: ./internal
        - action: rebuild
          path: ./cmd
