openapi: 3.0.0
info:
  version: 1.0.0
  title: Hex Forum Schema
paths:
  /forums:
    post:
      operationId: createForum
      description: ''
      summary: Create a Forum
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateForum'
      responses:
        201:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forum'
components:
  schemas:
    CreateForum:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        name:
          type: string
    Forum:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          x-go-type: googleuuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
            name: googleuuid
        name:
          type: string
