// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cjmarkham/hexplate/internal/api/pet"
	forum3 "github.com/cjmarkham/hexplate/internal/domain/pet"
	"github.com/cjmarkham/hexplate/internal/repository/mongo"
	forum2 "github.com/cjmarkham/hexplate/internal/repository/mongo/pet"
	"github.com/google/wire"
)

// Injectors from inject_main.go:

func injectApp() pet.Handlers {
	database := mongo.ProvideDatabase()
	collection := forum2.ProvideCollection(database)
	repository := forum2.ProvideRepository(collection)
	service := forum3.ProvideService(repository)
	handlers := pet.ProvideHandlers(service)
	return handlers
}

// inject_main.go:

var apiHandlers = wire.NewSet(pet.ProvideHandlers)

var domainHandlers = wire.NewSet(forum3.ProvideService)

var repositoryHandlers = wire.NewSet(mongo.ProvideDatabase, forum2.ProvideRepository, forum2.ProvideCollection, wire.Bind(new(forum3.Repository), new(forum2.Repository)))
